appearance:
  theme_day: minimal
  theme_night:
  font: native
  font_size: L

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'LOOPS Research Group'
    description: 'Learning and Optimisation Of Process Systems — UCL Department of Chemical Engineering'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true
    logo:
      filename: logo_purple.png

footer:
  copyright:
    notice: '© {year} LOOPS Research Group, UCL Department of Chemical Engineering'
    license:
      enable: false

locale:
  date_format: 'Jan 2006'
  time_format: '3:04 PM'
  address_format: en-gb

features:
  syntax_highlighter:
    enable: false
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/p-quintanilla/p-quintanilla.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
  search:
    provider: wowchemy
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

publications:
  date_format: January 2006
  citation_style: apa
